#!/bin/bash

# Post-provision script for AVD environment (Linux/macOS)
# This script provides instructions for manual configuration

echo "=== AVD Environment Post-Provision Instructions ==="
echo ""
echo "Since this is running on a non-Windows environment, please complete the following manual steps:"
echo ""
echo "1. Install Azure CLI if not already installed:"
echo "   curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
echo ""
echo "2. Login to Azure:"
echo "   az login"
echo ""
echo "3. Create Azure AD groups:"
echo "   az ad group create --display-name 'AVD Admins' --mail-nickname 'AVDAdmins'"
echo "   az ad group create --display-name 'AVD Users' --mail-nickname 'AVDUsers'"
echo ""
echo "4. Get storage account names:"
echo "   FSLOGIX_STORAGE=\$(az storage account list -g rg-$AZURE_ENV_NAME --query \"[?contains(name, 'fslogix')].name\" -o tsv)"
echo "   APPATTACH_STORAGE=\$(az storage account list -g rg-$AZURE_ENV_NAME --query \"[?contains(name, 'appattach')].name\" -o tsv)"
echo ""
echo "5. Get group IDs:"
echo "   ADMIN_GROUP_ID=\$(az ad group show --group 'AVD Admins' --query id -o tsv)"
echo "   USER_GROUP_ID=\$(az ad group show --group 'AVD Users' --query id -o tsv)"
echo ""
echo "6. Assign RBAC roles:"
echo "   # FSLogix storage roles"
echo "   az role assignment create --assignee \$ADMIN_GROUP_ID --role 'Storage File Data SMB Share Elevated Contributor' --scope /subscriptions/\$AZURE_SUBSCRIPTION_ID/resourceGroups/rg-\$AZURE_ENV_NAME/providers/Microsoft.Storage/storageAccounts/\$FSLOGIX_STORAGE"
echo "   az role assignment create --assignee \$USER_GROUP_ID --role 'Storage File Data SMB Share Contributor' --scope /subscriptions/\$AZURE_SUBSCRIPTION_ID/resourceGroups/rg-\$AZURE_ENV_NAME/providers/Microsoft.Storage/storageAccounts/\$FSLOGIX_STORAGE"
echo ""
echo "   # App Attach storage roles"
echo "   az role assignment create --assignee \$ADMIN_GROUP_ID --role 'Storage File Data SMB Share Elevated Contributor' --scope /subscriptions/\$AZURE_SUBSCRIPTION_ID/resourceGroups/rg-\$AZURE_ENV_NAME/providers/Microsoft.Storage/storageAccounts/\$APPATTACH_STORAGE"
echo ""
echo "7. Add users to groups:"
echo "   az ad group member add --group 'AVD Users' --member-id <user-object-id>"
echo "   az ad group member add --group 'AVD Admins' --member-id <admin-object-id>"
echo ""
echo "8. Configure session hosts (run PowerShell script on Windows machine):"
echo "   ./scripts/post-provision.ps1"
echo ""
echo "=== Manual Configuration Complete ==="
echo ""
echo "For detailed instructions, see the README.md file."